### ISSUE TITLE
Support for azure translation service

### ISSUE THREAD

**Issue by oleliabo** [fkirc/attranslate#159]
I have been using this tool with **--service=azure** but this support now seems to be removed? 

Last version with Azure support seems to be v1.4.1.

**Comment by fkirc** [comment]
Yes, but I would consider to re-add Azure support again.
In the meantime, 1.4.1 is the last version that works.
But if you revert parts of https://github.com/fkirc/attranslate/commit/dbdaf097fe48f78c075c30f4c60d12a2dbc1247d with a new PR, then we could merge it again.

**Comment by fkirc** [comment]
Released with v1.6.0
