### ISSUE TITLE
NOT BUG: how can translate all folder with yml files to other folder with another lang?

### ISSUE THREAD

**Issue by johnfelipe** [fkirc/attranslate#236]
![SNAG-0095](https://user-images.githubusercontent.com/428820/183090772-b7b51855-15fc-45a5-bd67-79f2f5039d6d.png)

al files is in **en** folder then i need all files to **es** folder

with will be command for google and azure?

GOOGLE WORKS:

`attranslate --srcFile=general.yml --srcLng=en --srcFormat=yaml --targetFile=general-es.yml --targetLng=es --targetFormat=yaml --service=google-translate --serviceConfig=traducciones-352415-79659df1c6f1.json`

**Comment by fkirc** [comment]
Hi,
Maybe the Readme-file is not clear about it, but the Azure-service expects you to pass an API-key as serviceConfig (not a JSON-filename!).

**Comment by johnfelipe** [comment]
`attranslate --srcFile=general.yml --srcLng=en --srcFormat=yaml --targetFile=general-es.yml --targetLng=es --targetFormat=yaml --service=google-translate --serviceConfig=traducciones-352415-79659df1c6f1.json`

can you share me command with azure for translate entire folder?

**Comment by fkirc** [comment]
I cannot share a complete Azure-command because I do not have an Azure-API-key right now.
But once you have a valid API-key, you can pass this API-key via `—serviceConfig=<yourAPIKey> —service=azure`. No other changes should be necessary.

**Comment by johnfelipe** [comment]
but for folder?

**Comment by fkirc** [comment]
To translate a folder, you need to invoke attranslate for each file separately.
But you could write a shell-script that does those invocations in parallel for all the files that you have in a given folder.

**Comment by johnfelipe** [comment]
ahh ok, like with others translator, may be like REQUEST and feature create
folder translator
tnks
