### ISSUE TITLE
JS translate

### ISSUE THREAD

**Issue by johnfelipe** [fkirc/attranslate#237]
https://github.com/louislam/uptime-kuma/blob/master/src/languages/en.js

is possible have JS translate into your great app?

**Comment by fkirc** [comment]
Sure, I would be happy to merge a PR that adds support for JS-translate!
It should be doable with only a few lines of code.

**Comment by johnfelipe** [comment]
ping me when is done pls my pal

**Comment by fkirc** [comment]
Hi, I apologize for the late response, I will look into it asap.
The attranslate project is currently underfunded and I am looking for viable business partners or sponsorings.
