### ISSUE TITLE
cant translate pot file en to es?

### ISSUE THREAD

**Issue by johnfelipe** [fkirc/attranslate#240]
https://gist.github.com/0b4ecd4380f47794c6f5a04f54d85325

`attranslate --srcFile=wp-erp/i18n/languages/erp.pot --srcLng=en --srcFormat=po --targetFile=wp-erp/i18n/languages/erp-es.pot --targetLng=es --targetFormat=po --service=google-translate --serviceConfig=traducciones-352415-79659df1c6f1.json`

and show me this

```
Bypass 7129 strings because they are empty...
Invoke 'google-translate' from 'en' to 'es' with 11 inputs...
Add 7140 new translations
Write target '/root/attranslate/wp-erp/i18n/languages/erp-es.pot'

```
https://gist.github.com/1b715430007ff5aec99af3594a3b7010

tnks for your help in this one

im using before this one https://github.com/sourcecodeit/po-gtranslator

**Comment by fkirc** [comment]
Hi, I apologize for the late response, I will look into it asap.
The attranslate project is currently underfunded and I am looking for viable business partners or sponsorings.
