### ISSUE TITLE
Double quotes in Localizable.strings

### ISSUE THREAD

**Issue by yoman07** [fkirc/attranslate#241]
**Describe the bug**
If I run script to convert android xml to iOS Localizable.strings I have double quotes:

Android source:
    <string name="incorrect_id">"Incorrect id"</string>

Actual results:
"incorrect_id" = ""Incorrect id.";

Expect results:
"incorrect_id" = "Incorrect id. ";

**To Reproduce**
```
ANDROID_EN="app/src/main/res/external/strings/values/strings.xml"
iOS_EN="/Base.lproj/Localizable.strings"

ANDROID_TO_iOS=( "--srcFormat=xml" "--targetFormat=ios-strings" "--service=sync-without-translate" "--cacheDir=android")

attranslate "${ANDROID_TO_iOS[@]}" --srcFile=$ANDROID_EN --targetFile=$iOS_EN --srcLng="en" --targetLng="en"

```
**Expected behavior**
Expect results:
"incorrect_id" = "Incorrect id. ";

**Comment by fkirc** [comment]
Hi, I apologize for the late response, I will look into it asap.
The attranslate project is currently underfunded and I am looking for viable business partners or sponsorings.
